set-option -g history-limit 25000
bind-key v set -g mouse

# for neovim
set -sg escape-time 10
set-option -g focus-events on

# vi for copy mode
setw -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection-and-cancel

# status bar
set -g status-bg default
set -g status-position top
set -g status-interval 1
set -g status-right-length 250
set -g status-right "#( ~/.tmux/status.sh)"

# count the panes from 1
set -g base-index 1
setw -g pane-base-index 1

# new windows in same dir
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# set name of window to pwd
set-option -g automatic-rename on
set-option -g automatic-rename-format '#{b:pane_current_path}'
